[
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     829     gcc: _configtest.c\n830     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     831         3 | #pragma clang diagnostic error \"-Wattributes\"\n     832           |\n     833     _configtest.c: In function '__declspec':\n  >> 834     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "835         5 | int __declspec(thread) foo;\n     836           |                        ^~~\n  >> 837     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     838         9 | {\n     839           | ^\n840     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     841         5 | int __declspec(thread) foo;\n     842           |     ^~~~~~~~~~\n  >> 843     _configtest.c:11: error: expected '{' at end of input\n     844        11 | }\n     845           |",
    "implicit-int]\n     841         5 | int __declspec(thread) foo;\n     842           |     ^~~~~~~~~~\n  >> 843     _configtest.c:11: error: expected '{' at end of input\n     844        11 | }\n     845           |\n846     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     847        11 | }\n     848           |\n     849     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     850         3 | #pragma clang diagnostic error \"-Wattributes\"",
    "844        11 | }\n     845           |\n     846     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     847        11 | }\n     848           |\n849     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     850         3 | #pragma clang diagnostic error \"-Wattributes\"\n     851           |\n     852     _configtest.c: In function '__declspec':\n  >> 853     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "854         5 | int __declspec(thread) foo;\n     855           |                        ^~~\n  >> 856     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     857         9 | {\n     858           | ^\n859     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     860         5 | int __declspec(thread) foo;\n     861           |     ^~~~~~~~~~\n  >> 862     _configtest.c:11: error: expected '{' at end of input\n     863        11 | }\n     864           |",
    "implicit-int]\n     860         5 | int __declspec(thread) foo;\n     861           |     ^~~~~~~~~~\n  >> 862     _configtest.c:11: error: expected '{' at end of input\n     863        11 | }\n     864           |\n865     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     866        11 | }\n     867           |\n     868     failure.\n\n     ...",
    "z56muf3y24twbgptm5fwkbrmdx/lib/python3.8/site-packages/setuptools/\n             command/install.py:34: SetuptoolsDeprecationWarning: setup.py inst\n             all is deprecated. Use build and pip and other standards-based too\n             ls.\n     4056      warnings.warn(\n     4057    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n4058    numpy/random/mtrand/mtrand.c:42495:3: warning: 'tp_print' is depre\n             cated [-Wdeprecated-declarations]\n     4059    42495 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4060          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4061    In file included from /p/vast1/koparasy/BUILD/spack_cluster_instal\n             ler/quartz/nrm/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/pytho\n             n-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/include/python3.8/object",
    "st.o -o _configtest\n     98      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 99      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 100     collect2: error: ld returned 1 exit status\n     101     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 102     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 103     collect2: error: ld returned 1 exit status",
    ">> 100     collect2: error: ld returned 1 exit status\n     101     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 102     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 103     collect2: error: ld returned 1 exit status\n     104     failure.\n     105     removing: _configtest.c _configtest.o\n     106     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     107",
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     154     gcc: _configtest.c\n>> 155     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     156         1 | #include <sys/endian.h>\n     157           |          ^~~~~~~~~~~~~~\n     158     compilation terminated.\n  >> 159     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory",
    "154     gcc: _configtest.c\n  >> 155     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     156         1 | #include <sys/endian.h>\n     157           |          ^~~~~~~~~~~~~~\n     158     compilation terminated.\n>> 159     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     160         1 | #include <sys/endian.h>\n     161           |          ^~~~~~~~~~~~~~\n     162     compilation terminated.\n     163     failure.\n     164     removing: _configtest.c _configtest.o",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     270     gcc: _configtest.c\n     271     _configtest.c: In function 'main':\n>> 272     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     273         7 |     (void) SIZEOF_LONGDOUBLE;\n     274           |            ^~~~~~~~~~~~~~~~~\n     275           |            SIZEOF_LONG_DOUBLE\n     276     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "273         7 |     (void) SIZEOF_LONGDOUBLE;\n     274           |            ^~~~~~~~~~~~~~~~~\n     275           |            SIZEOF_LONG_DOUBLE\n     276     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     277     _configtest.c: In function 'main':\n>> 278     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     279         7 |     (void) SIZEOF_LONGDOUBLE;\n     280           |            ^~~~~~~~~~~~~~~~~\n     281           |            SIZEOF_LONG_DOUBLE\n     282     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     416     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 417     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 418     collect2: error: ld returned 1 exit status\n     419     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 420     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 421     collect2: error: ld returned 1 exit status",
    ">> 418     collect2: error: ld returned 1 exit status\n     419     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 420     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 421     collect2: error: ld returned 1 exit status\n     422     failure.\n     423     removing: _configtest.c _configtest.o\n     424     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     425",
    "829     gcc: _configtest.c\n     830     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     831         3 | #pragma clang diagnostic error \"-Wattributes\"\n     832           |\n     833     _configtest.c: In function '__declspec':\n>> 834     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     835         5 | int __declspec(thread) foo;\n     836           |                        ^~~\n  >> 837     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     838         9 | {",
    "832           |\n     833     _configtest.c: In function '__declspec':\n  >> 834     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     835         5 | int __declspec(thread) foo;\n     836           |                        ^~~\n>> 837     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     838         9 | {\n     839           | ^\n     840     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     841         5 | int __declspec(thread) foo;",
    "838         9 | {\n     839           | ^\n     840     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     841         5 | int __declspec(thread) foo;\n     842           |     ^~~~~~~~~~\n>> 843     _configtest.c:11: error: expected '{' at end of input\n     844        11 | }\n     845           |\n     846     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     847        11 | }\n     848           |",
    "848           |\n     849     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     850         3 | #pragma clang diagnostic error \"-Wattributes\"\n     851           |\n     852     _configtest.c: In function '__declspec':\n>> 853     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     854         5 | int __declspec(thread) foo;\n     855           |                        ^~~\n  >> 856     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     857         9 | {",
    "851           |\n     852     _configtest.c: In function '__declspec':\n  >> 853     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     854         5 | int __declspec(thread) foo;\n     855           |                        ^~~\n>> 856     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     857         9 | {\n     858           | ^\n     859     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     860         5 | int __declspec(thread) foo;",
    "857         9 | {\n     858           | ^\n     859     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     860         5 | int __declspec(thread) foo;\n     861           |     ^~~~~~~~~~\n>> 862     _configtest.c:11: error: expected '{' at end of input\n     863        11 | }\n     864           |\n     865     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     866        11 | }\n     867           |",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     1195    gcc: _configtest.c\n     1196    _configtest.c: In function 'main':\n>> 1197    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1198        8 |     (void) HAVE_DECL_SIGNBIT;\n     1199          |            ^~~~~~~~~~~~~~~~~\n     1200          |            HAVE_DECL_ISNAN\n     1201    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "1198        8 |     (void) HAVE_DECL_SIGNBIT;\n     1199          |            ^~~~~~~~~~~~~~~~~\n     1200          |            HAVE_DECL_ISNAN\n     1201    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     1202    _configtest.c: In function 'main':\n>> 1203    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1204        8 |     (void) HAVE_DECL_SIGNBIT;\n     1205          |            ^~~~~~~~~~~~~~~~~\n     1206          |            HAVE_DECL_ISNAN\n     1207    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1791    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1792    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1793    collect2: error: ld returned 1 exit status\n     1794    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1795    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 1796    collect2: error: ld returned 1 exit status",
    ">> 1793    collect2: error: ld returned 1 exit status\n     1794    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1795    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.12.1-fffs44oiub6l\n             qennwfcsvrpmf6j4zagc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1796    collect2: error: ld returned 1 exit status\n     1797    failure.\n     1798    removing: _configtest.c _configtest.o\n     1799    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1800",
    "e: declared here\n     3981      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     3982          |                              ^~~~~~~~\n     3983    numpy/random/mtrand/mtrand.c: In function '__Pyx_PyCFunction_FastC\n             all':\n>> 3984    numpy/random/mtrand/mtrand.c:44104:13: error: too many arguments t\n             o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     3985    44104 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     3986          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     3987    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':",
    "o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     3985    44104 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     3986          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     3987    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 3988    numpy/random/mtrand/mtrand.c:44523:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3989    44523 |     *type = tstate->exc_type;\n     3990          |                     ^~~~~~~~\n     3991          |                     curexc_type\n  >> 3992    numpy/random/mtrand/mtrand.c:44524:22: error: 'PyThreadState' {aka",
    ">> 3988    numpy/random/mtrand/mtrand.c:44523:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3989    44523 |     *type = tstate->exc_type;\n     3990          |                     ^~~~~~~~\n     3991          |                     curexc_type\n>> 3992    numpy/random/mtrand/mtrand.c:44524:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3993    44524 |     *value = tstate->exc_value;\n     3994          |                      ^~~~~~~~~\n     3995          |                      curexc_value\n  >> 3996    numpy/random/mtrand/mtrand.c:44525:19: error: 'PyThreadState' {aka",
    ">> 3992    numpy/random/mtrand/mtrand.c:44524:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3993    44524 |     *value = tstate->exc_value;\n     3994          |                      ^~~~~~~~~\n     3995          |                      curexc_value\n>> 3996    numpy/random/mtrand/mtrand.c:44525:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3997    44525 |     *tb = tstate->exc_traceback;\n     3998          |                   ^~~~~~~~~~~~~\n     3999          |                   curexc_traceback\n     4000    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3997    44525 |     *tb = tstate->exc_traceback;\n     3998          |                   ^~~~~~~~~~~~~\n     3999          |                   curexc_traceback\n     4000    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4001    numpy/random/mtrand/mtrand.c:44532:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4002    44532 |     tmp_type = tstate->exc_type;\n     4003          |                        ^~~~~~~~\n     4004          |                        curexc_type\n  >> 4005    numpy/random/mtrand/mtrand.c:44533:25: error: 'PyThreadState' {aka",
    ">> 4001    numpy/random/mtrand/mtrand.c:44532:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4002    44532 |     tmp_type = tstate->exc_type;\n     4003          |                        ^~~~~~~~\n     4004          |                        curexc_type\n>> 4005    numpy/random/mtrand/mtrand.c:44533:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4006    44533 |     tmp_value = tstate->exc_value;\n     4007          |                         ^~~~~~~~~\n     4008          |                         curexc_value\n  >> 4009    numpy/random/mtrand/mtrand.c:44534:22: error: 'PyThreadState' {aka",
    ">> 4005    numpy/random/mtrand/mtrand.c:44533:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4006    44533 |     tmp_value = tstate->exc_value;\n     4007          |                         ^~~~~~~~~\n     4008          |                         curexc_value\n>> 4009    numpy/random/mtrand/mtrand.c:44534:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4010    44534 |     tmp_tb = tstate->exc_traceback;\n     4011          |                      ^~~~~~~~~~~~~\n     4012          |                      curexc_traceback\n  >> 4013    numpy/random/mtrand/mtrand.c:44535:13: error: 'PyThreadState' {aka",
    ">> 4009    numpy/random/mtrand/mtrand.c:44534:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4010    44534 |     tmp_tb = tstate->exc_traceback;\n     4011          |                      ^~~~~~~~~~~~~\n     4012          |                      curexc_traceback\n>> 4013    numpy/random/mtrand/mtrand.c:44535:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4014    44535 |     tstate->exc_type = type;\n     4015          |             ^~~~~~~~\n     4016          |             curexc_type\n  >> 4017    numpy/random/mtrand/mtrand.c:44536:13: error: 'PyThreadState' {aka",
    ">> 4013    numpy/random/mtrand/mtrand.c:44535:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4014    44535 |     tstate->exc_type = type;\n     4015          |             ^~~~~~~~\n     4016          |             curexc_type\n>> 4017    numpy/random/mtrand/mtrand.c:44536:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4018    44536 |     tstate->exc_value = value;\n     4019          |             ^~~~~~~~~\n     4020          |             curexc_value\n  >> 4021    numpy/random/mtrand/mtrand.c:44537:13: error: 'PyThreadState' {aka",
    ">> 4017    numpy/random/mtrand/mtrand.c:44536:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4018    44536 |     tstate->exc_value = value;\n     4019          |             ^~~~~~~~~\n     4020          |             curexc_value\n>> 4021    numpy/random/mtrand/mtrand.c:44537:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4022    44537 |     tstate->exc_traceback = tb;\n     4023          |             ^~~~~~~~~~~~~\n     4024          |             curexc_traceback\n     4025    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4022    44537 |     tstate->exc_traceback = tb;\n     4023          |             ^~~~~~~~~~~~~\n     4024          |             curexc_traceback\n     4025    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4026    numpy/random/mtrand/mtrand.c:44592:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4027    44592 |     tmp_type = tstate->exc_type;\n     4028          |                        ^~~~~~~~\n     4029          |                        curexc_type\n  >> 4030    numpy/random/mtrand/mtrand.c:44593:25: error: 'PyThreadState' {aka",
    ">> 4026    numpy/random/mtrand/mtrand.c:44592:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4027    44592 |     tmp_type = tstate->exc_type;\n     4028          |                        ^~~~~~~~\n     4029          |                        curexc_type\n>> 4030    numpy/random/mtrand/mtrand.c:44593:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4031    44593 |     tmp_value = tstate->exc_value;\n     4032          |                         ^~~~~~~~~\n     4033          |                         curexc_value\n  >> 4034    numpy/random/mtrand/mtrand.c:44594:22: error: 'PyThreadState' {aka",
    ">> 4030    numpy/random/mtrand/mtrand.c:44593:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4031    44593 |     tmp_value = tstate->exc_value;\n     4032          |                         ^~~~~~~~~\n     4033          |                         curexc_value\n>> 4034    numpy/random/mtrand/mtrand.c:44594:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4035    44594 |     tmp_tb = tstate->exc_traceback;\n     4036          |                      ^~~~~~~~~~~~~\n     4037          |                      curexc_traceback\n  >> 4038    numpy/random/mtrand/mtrand.c:44595:13: error: 'PyThreadState' {aka",
    ">> 4034    numpy/random/mtrand/mtrand.c:44594:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4035    44594 |     tmp_tb = tstate->exc_traceback;\n     4036          |                      ^~~~~~~~~~~~~\n     4037          |                      curexc_traceback\n>> 4038    numpy/random/mtrand/mtrand.c:44595:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4039    44595 |     tstate->exc_type = local_type;\n     4040          |             ^~~~~~~~\n     4041          |             curexc_type\n  >> 4042    numpy/random/mtrand/mtrand.c:44596:13: error: 'PyThreadState' {aka",
    ">> 4038    numpy/random/mtrand/mtrand.c:44595:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4039    44595 |     tstate->exc_type = local_type;\n     4040          |             ^~~~~~~~\n     4041          |             curexc_type\n>> 4042    numpy/random/mtrand/mtrand.c:44596:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4043    44596 |     tstate->exc_value = local_value;\n     4044          |             ^~~~~~~~~\n     4045          |             curexc_value\n  >> 4046    numpy/random/mtrand/mtrand.c:44597:13: error: 'PyThreadState' {aka",
    ">> 4042    numpy/random/mtrand/mtrand.c:44596:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4043    44596 |     tstate->exc_value = local_value;\n     4044          |             ^~~~~~~~~\n     4045          |             curexc_value\n>> 4046    numpy/random/mtrand/mtrand.c:44597:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4047    44597 |     tstate->exc_traceback = local_tb;\n     4048          |             ^~~~~~~~~~~~~\n     4049          |             curexc_traceback\n     4050    Running from numpy source directory.",
    "e: declared here\n     4066      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     4067          |                              ^~~~~~~~\n     4068    numpy/random/mtrand/mtrand.c: In function '__Pyx_PyCFunction_FastC\n             all':\n>> 4069    numpy/random/mtrand/mtrand.c:44104:13: error: too many arguments t\n             o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     4070    44104 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     4071          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4072    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':",
    "o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     4070    44104 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     4071          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4072    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4073    numpy/random/mtrand/mtrand.c:44523:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4074    44523 |     *type = tstate->exc_type;\n     4075          |                     ^~~~~~~~\n     4076          |                     curexc_type\n  >> 4077    numpy/random/mtrand/mtrand.c:44524:22: error: 'PyThreadState' {aka",
    ">> 4073    numpy/random/mtrand/mtrand.c:44523:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4074    44523 |     *type = tstate->exc_type;\n     4075          |                     ^~~~~~~~\n     4076          |                     curexc_type\n>> 4077    numpy/random/mtrand/mtrand.c:44524:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4078    44524 |     *value = tstate->exc_value;\n     4079          |                      ^~~~~~~~~\n     4080          |                      curexc_value\n  >> 4081    numpy/random/mtrand/mtrand.c:44525:19: error: 'PyThreadState' {aka",
    ">> 4077    numpy/random/mtrand/mtrand.c:44524:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4078    44524 |     *value = tstate->exc_value;\n     4079          |                      ^~~~~~~~~\n     4080          |                      curexc_value\n>> 4081    numpy/random/mtrand/mtrand.c:44525:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4082    44525 |     *tb = tstate->exc_traceback;\n     4083          |                   ^~~~~~~~~~~~~\n     4084          |                   curexc_traceback\n     4085    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4082    44525 |     *tb = tstate->exc_traceback;\n     4083          |                   ^~~~~~~~~~~~~\n     4084          |                   curexc_traceback\n     4085    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4086    numpy/random/mtrand/mtrand.c:44532:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4087    44532 |     tmp_type = tstate->exc_type;\n     4088          |                        ^~~~~~~~\n     4089          |                        curexc_type\n  >> 4090    numpy/random/mtrand/mtrand.c:44533:25: error: 'PyThreadState' {aka",
    ">> 4086    numpy/random/mtrand/mtrand.c:44532:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4087    44532 |     tmp_type = tstate->exc_type;\n     4088          |                        ^~~~~~~~\n     4089          |                        curexc_type\n>> 4090    numpy/random/mtrand/mtrand.c:44533:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4091    44533 |     tmp_value = tstate->exc_value;\n     4092          |                         ^~~~~~~~~\n     4093          |                         curexc_value\n  >> 4094    numpy/random/mtrand/mtrand.c:44534:22: error: 'PyThreadState' {aka",
    ">> 4090    numpy/random/mtrand/mtrand.c:44533:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4091    44533 |     tmp_value = tstate->exc_value;\n     4092          |                         ^~~~~~~~~\n     4093          |                         curexc_value\n>> 4094    numpy/random/mtrand/mtrand.c:44534:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4095    44534 |     tmp_tb = tstate->exc_traceback;\n     4096          |                      ^~~~~~~~~~~~~\n     4097          |                      curexc_traceback\n  >> 4098    numpy/random/mtrand/mtrand.c:44535:13: error: 'PyThreadState' {aka",
    ">> 4094    numpy/random/mtrand/mtrand.c:44534:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4095    44534 |     tmp_tb = tstate->exc_traceback;\n     4096          |                      ^~~~~~~~~~~~~\n     4097          |                      curexc_traceback\n>> 4098    numpy/random/mtrand/mtrand.c:44535:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4099    44535 |     tstate->exc_type = type;\n     4100          |             ^~~~~~~~\n     4101          |             curexc_type\n  >> 4102    numpy/random/mtrand/mtrand.c:44536:13: error: 'PyThreadState' {aka",
    ">> 4098    numpy/random/mtrand/mtrand.c:44535:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4099    44535 |     tstate->exc_type = type;\n     4100          |             ^~~~~~~~\n     4101          |             curexc_type\n>> 4102    numpy/random/mtrand/mtrand.c:44536:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4103    44536 |     tstate->exc_value = value;\n     4104          |             ^~~~~~~~~\n     4105          |             curexc_value\n  >> 4106    numpy/random/mtrand/mtrand.c:44537:13: error: 'PyThreadState' {aka",
    ">> 4102    numpy/random/mtrand/mtrand.c:44536:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4103    44536 |     tstate->exc_value = value;\n     4104          |             ^~~~~~~~~\n     4105          |             curexc_value\n>> 4106    numpy/random/mtrand/mtrand.c:44537:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4107    44537 |     tstate->exc_traceback = tb;\n     4108          |             ^~~~~~~~~~~~~\n     4109          |             curexc_traceback\n     4110    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4107    44537 |     tstate->exc_traceback = tb;\n     4108          |             ^~~~~~~~~~~~~\n     4109          |             curexc_traceback\n     4110    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4111    numpy/random/mtrand/mtrand.c:44592:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4112    44592 |     tmp_type = tstate->exc_type;\n     4113          |                        ^~~~~~~~\n     4114          |                        curexc_type\n  >> 4115    numpy/random/mtrand/mtrand.c:44593:25: error: 'PyThreadState' {aka",
    ">> 4111    numpy/random/mtrand/mtrand.c:44592:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4112    44592 |     tmp_type = tstate->exc_type;\n     4113          |                        ^~~~~~~~\n     4114          |                        curexc_type\n>> 4115    numpy/random/mtrand/mtrand.c:44593:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4116    44593 |     tmp_value = tstate->exc_value;\n     4117          |                         ^~~~~~~~~\n     4118          |                         curexc_value\n  >> 4119    numpy/random/mtrand/mtrand.c:44594:22: error: 'PyThreadState' {aka",
    ">> 4115    numpy/random/mtrand/mtrand.c:44593:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4116    44593 |     tmp_value = tstate->exc_value;\n     4117          |                         ^~~~~~~~~\n     4118          |                         curexc_value\n>> 4119    numpy/random/mtrand/mtrand.c:44594:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4120    44594 |     tmp_tb = tstate->exc_traceback;\n     4121          |                      ^~~~~~~~~~~~~\n     4122          |                      curexc_traceback\n  >> 4123    numpy/random/mtrand/mtrand.c:44595:13: error: 'PyThreadState' {aka",
    ">> 4119    numpy/random/mtrand/mtrand.c:44594:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4120    44594 |     tmp_tb = tstate->exc_traceback;\n     4121          |                      ^~~~~~~~~~~~~\n     4122          |                      curexc_traceback\n>> 4123    numpy/random/mtrand/mtrand.c:44595:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4124    44595 |     tstate->exc_type = local_type;\n     4125          |             ^~~~~~~~\n     4126          |             curexc_type\n  >> 4127    numpy/random/mtrand/mtrand.c:44596:13: error: 'PyThreadState' {aka",
    ">> 4123    numpy/random/mtrand/mtrand.c:44595:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4124    44595 |     tstate->exc_type = local_type;\n     4125          |             ^~~~~~~~\n     4126          |             curexc_type\n>> 4127    numpy/random/mtrand/mtrand.c:44596:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4128    44596 |     tstate->exc_value = local_value;\n     4129          |             ^~~~~~~~~\n     4130          |             curexc_value\n  >> 4131    numpy/random/mtrand/mtrand.c:44597:13: error: 'PyThreadState' {aka",
    ">> 4127    numpy/random/mtrand/mtrand.c:44596:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4128    44596 |     tstate->exc_value = local_value;\n     4129          |             ^~~~~~~~~\n     4130          |             curexc_value\n>> 4131    numpy/random/mtrand/mtrand.c:44597:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4132    44597 |     tstate->exc_traceback = local_tb;\n     4133          |             ^~~~~~~~~~~~~\n     4134          |             curexc_traceback\n  >> 4135    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g"
]