[
    "3794           |                                    ^\n  >> 3795    src/mpi4py.MPI.c:161122:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3796    161122 |   __pyx_type_6mpi4py_3MPI_Pickle.tp_print = 0;\n     3797           |                                 ^\n     3798    src/mpi4py.MPI.c: In function '__Pyx_ParseOptionalKeywords':\n3799    src/mpi4py.MPI.c:174013:21: warning: '_PyUnicode_get_wstr_length'\n             is deprecated [-Wdeprecated-declarations]\n     3800    174013 |                     (PyUnicode_GET_SIZE(**name) != PyUnic\n             ode_GET_SIZE(key)) ? 1 :\n     3801           |                     ^\n\n     ...",
    "c -o _configtest.o\n     39      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -llmpe -o _\n             configtest\n  >> 40      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\nedhat-linux/9/ld: cannot find -llmpe\n  >> 41      collect2: error: ld returned 1 exit status\n     42      failure.\n     43      removing: _configtest.c _configtest.o\n     44      building 'mpe' dylib library\n     45      creating build/temp.linux-x86_64-3.9\n     46      creating build/temp.linux-x86_64-3.9/src",
    "39      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -llmpe -o _\n             configtest\n  >> 40      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: cannot find -llmpe\n>> 41      collect2: error: ld returned 1 exit status\n     42      failure.\n     43      removing: _configtest.c _configtest.o\n     44      building 'mpe' dylib library\n     45      creating build/temp.linux-x86_64-3.9\n     46      creating build/temp.linux-x86_64-3.9/src\n     47      creating build/temp.linux-x86_64-3.9/src/lib-pmpi",
    "c -o _configtest.o\n     53      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt-mpi -o\n              _configtest\n  >> 54      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\nedhat-linux/9/ld: cannot find -lvt-mpi\n  >> 55      collect2: error: ld returned 1 exit status\n     56      failure.\n     57      removing: _configtest.c _configtest.o\n     58      checking for library 'vt.mpi' ...\n     59      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx",
    "53      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt-mpi -o\n              _configtest\n  >> 54      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: cannot find -lvt-mpi\n>> 55      collect2: error: ld returned 1 exit status\n     56      failure.\n     57      removing: _configtest.c _configtest.o\n     58      checking for library 'vt.mpi' ...\n     59      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc -Wno-unused-result -Wsign",
    "c -o _configtest.o\n     60      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt.mpi -o\n              _configtest\n  >> 61      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\nedhat-linux/9/ld: cannot find -lvt.mpi\n  >> 62      collect2: error: ld returned 1 exit status\n     63      failure.\n     64      removing: _configtest.c _configtest.o\n     65      building 'vt' dylib library\n     66      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx",
    "60      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt.mpi -o\n              _configtest\n  >> 61      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: cannot find -lvt.mpi\n>> 62      collect2: error: ld returned 1 exit status\n     63      failure.\n     64      removing: _configtest.c _configtest.o\n     65      building 'vt' dylib library\n     66      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc -Wno-unused-result -Wsign",
    "c -o _configtest.o\n     70      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt-mpi -o\n              _configtest\n  >> 71      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\nedhat-linux/9/ld: cannot find -lvt-mpi\n  >> 72      collect2: error: ld returned 1 exit status\n     73      failure.\n     74      removing: _configtest.c _configtest.o\n     75      checking for library 'vt.mpi' ...\n     76      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx",
    "70      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt-mpi -o\n              _configtest\n  >> 71      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: cannot find -lvt-mpi\n>> 72      collect2: error: ld returned 1 exit status\n     73      failure.\n     74      removing: _configtest.c _configtest.o\n     75      checking for library 'vt.mpi' ...\n     76      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc -Wno-unused-result -Wsign",
    "c -o _configtest.o\n     77      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt.mpi -o\n              _configtest\n  >> 78      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\nedhat-linux/9/ld: cannot find -lvt.mpi\n  >> 79      collect2: error: ld returned 1 exit status\n     80      failure.\n     81      removing: _configtest.c _configtest.o\n     82      building 'vt-mpi' dylib library\n     83      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx",
    "77      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt.mpi -o\n              _configtest\n  >> 78      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: cannot find -lvt.mpi\n>> 79      collect2: error: ld returned 1 exit status\n     80      failure.\n     81      removing: _configtest.c _configtest.o\n     82      building 'vt-mpi' dylib library\n     83      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc -Wno-unused-result -Wsign",
    "c -o _configtest.o\n     87      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt-hyb -o\n              _configtest\n  >> 88      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\nedhat-linux/9/ld: cannot find -lvt-hyb\n  >> 89      collect2: error: ld returned 1 exit status\n     90      failure.\n     91      removing: _configtest.c _configtest.o\n     92      checking for library 'vt.ompi' ...\n     93      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx",
    "87      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt-hyb -o\n              _configtest\n  >> 88      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: cannot find -lvt-hyb\n>> 89      collect2: error: ld returned 1 exit status\n     90      failure.\n     91      removing: _configtest.c _configtest.o\n     92      checking for library 'vt.ompi' ...\n     93      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc -Wno-unused-result -Wsign",
    "c -o _configtest.o\n     94      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt.ompi -\n             o _configtest\n  >> 95      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\nedhat-linux/9/ld: cannot find -lvt.ompi\n  >> 96      collect2: error: ld returned 1 exit status\n     97      failure.\n     98      removing: _configtest.c _configtest.o\n     99      building 'vt-hyb' dylib library\n     100     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx",
    "94      /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc _configtest.o -lvt.ompi -\n             o _configtest\n  >> 95      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: cannot find -lvt.ompi\n>> 96      collect2: error: ld returned 1 exit status\n     97      failure.\n     98      removing: _configtest.c _configtest.o\n     99      building 'vt-hyb' dylib library\n     100     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem\n             ble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-develop-yx\n             tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc -Wno-unused-result -Wsign",
    "tfk2dhopsmw7iihcigbglb5m6nrvtt/bin/mpicc -Wno-unused-result -Wsign\n             -compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/p/vast1/kopa\n             rasy/BUILD/spack_cluster_installer/quartz/py-libensemble/spack_env\n             _dir/linux-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxw\n             x2ytcv7sd3g35si6/include/python3.9 -c _configtest.c -o _configtest\n             .o\n>> 137     _configtest.c:5:2: error: #error \"Unknown MPI implementation\"\n     138         5 | #error \"Unknown MPI implementation\"\n     139           |  ^~~~~\n     140     failure.\n     141     removing: _configtest.c _configtest.o\n     142     checking for 'MPI_Aint' ...\n     143     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensem",
    "-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/p/vast1/kopa\n             rasy/BUILD/spack_cluster_installer/quartz/py-libensemble/spack_env\n             _dir/linux-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxw\n             x2ytcv7sd3g35si6/include/python3.9 -c _configtest.c -o _configtest\n             .o\n     539     _configtest.c: In function 'main':\n>> 540     _configtest.c:6:23: error: 'MPI_LOGICAL1' undeclared (first use in\n              this function); did you mean 'MPI_LOGICAL'?\n     541         6 |   MPI_Datatype v; v = MPI_LOGICAL1; (void)v;\n     542           |                       ^~~~~~~~~~~~\n     543           |                       MPI_LOGICAL\n     544     _configtest.c:6:23: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/p/vast1/kopa\n             rasy/BUILD/spack_cluster_installer/quartz/py-libensemble/spack_env\n             _dir/linux-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxw\n             x2ytcv7sd3g35si6/include/python3.9 -c _configtest.c -o _configtest\n             .o\n     550     _configtest.c: In function 'main':\n>> 551     _configtest.c:6:23: error: 'MPI_LOGICAL2' undeclared (first use in\n              this function); did you mean 'MPI_LOGICAL'?\n     552         6 |   MPI_Datatype v; v = MPI_LOGICAL2; (void)v;\n     553           |                       ^~~~~~~~~~~~\n     554           |                       MPI_LOGICAL\n     555     _configtest.c:6:23: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/p/vast1/kopa\n             rasy/BUILD/spack_cluster_installer/quartz/py-libensemble/spack_env\n             _dir/linux-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxw\n             x2ytcv7sd3g35si6/include/python3.9 -c _configtest.c -o _configtest\n             .o\n     561     _configtest.c: In function 'main':\n>> 562     _configtest.c:6:23: error: 'MPI_LOGICAL4' undeclared (first use in\n              this function); did you mean 'MPI_LOGICAL'?\n     563         6 |   MPI_Datatype v; v = MPI_LOGICAL4; (void)v;\n     564           |                       ^~~~~~~~~~~~\n     565           |                       MPI_LOGICAL\n     566     _configtest.c:6:23: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/p/vast1/kopa\n             rasy/BUILD/spack_cluster_installer/quartz/py-libensemble/spack_env\n             _dir/linux-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxw\n             x2ytcv7sd3g35si6/include/python3.9 -c _configtest.c -o _configtest\n             .o\n     572     _configtest.c: In function 'main':\n>> 573     _configtest.c:6:23: error: 'MPI_LOGICAL8' undeclared (first use in\n              this function); did you mean 'MPI_LOGICAL'?\n     574         6 |   MPI_Datatype v; v = MPI_LOGICAL8; (void)v;\n     575           |                       ^~~~~~~~~~~~\n     576           |                       MPI_LOGICAL\n     577     _configtest.c:6:23: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/p/vast1/kopa\n             rasy/BUILD/spack_cluster_installer/quartz/py-libensemble/spack_env\n             _dir/linux-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxw\n             x2ytcv7sd3g35si6/include/python3.9 -c _configtest.c -o _configtest\n             .o\n     608     _configtest.c: In function 'main':\n>> 609     _configtest.c:6:23: error: 'MPI_REAL2' undeclared (first use in th\n             is function); did you mean 'MPI_REAL8'?\n     610         6 |   MPI_Datatype v; v = MPI_REAL2; (void)v;\n     611           |                       ^~~~~~~~~\n     612           |                       MPI_REAL8\n     613     _configtest.c:6:23: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/p/vast1/kopa\n             rasy/BUILD/spack_cluster_installer/quartz/py-libensemble/spack_env\n             _dir/linux-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxw\n             x2ytcv7sd3g35si6/include/python3.9 -c _configtest.c -o _configtest\n             .o\n     634     _configtest.c: In function 'main':\n>> 635     _configtest.c:6:23: error: 'MPI_COMPLEX4' undeclared (first use in\n              this function); did you mean 'MPI_COMPLEX'?\n     636         6 |   MPI_Datatype v; v = MPI_COMPLEX4; (void)v;\n     637           |                       ^~~~~~~~~~~~\n     638           |                       MPI_COMPLEX\n     639     _configtest.c:6:23: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "k_cluster_installer/quartz/py-libensemble/spack_env_dir/linux-rhel\n             7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si\n             6/include/python3.9 -c src/MPI.c -o build/temp.linux-x86_64-3.9/sr\n             c/MPI.o\n     3703    In file included from src/MPI.c:4:\n     3704    src/mpi4py.MPI.c: In function '__Pyx_modinit_type_init_code':\n>> 3705    src/mpi4py.MPI.c:160852:19: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3706    160852 |   PyMPIStatus_Type.tp_print = 0;\n     3707           |                   ^\n  >> 3708    src/mpi4py.MPI.c:160859:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3709    160859 |   PyMPIDatatype_Type.tp_print = 0;",
    "3703    In file included from src/MPI.c:4:\n     3704    src/mpi4py.MPI.c: In function '__Pyx_modinit_type_init_code':\n  >> 3705    src/mpi4py.MPI.c:160852:19: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3706    160852 |   PyMPIStatus_Type.tp_print = 0;\n     3707           |                   ^\n>> 3708    src/mpi4py.MPI.c:160859:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3709    160859 |   PyMPIDatatype_Type.tp_print = 0;\n     3710           |                     ^\n  >> 3711    src/mpi4py.MPI.c:160866:20: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3712    160866 |   PyMPIRequest_Type.tp_print = 0;",
    "3706    160852 |   PyMPIStatus_Type.tp_print = 0;\n     3707           |                   ^\n  >> 3708    src/mpi4py.MPI.c:160859:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3709    160859 |   PyMPIDatatype_Type.tp_print = 0;\n     3710           |                     ^\n>> 3711    src/mpi4py.MPI.c:160866:20: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3712    160866 |   PyMPIRequest_Type.tp_print = 0;\n     3713           |                    ^\n  >> 3714    src/mpi4py.MPI.c:160874:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3715    160874 |   PyMPIPrequest_Type.tp_print = 0;",
    "3709    160859 |   PyMPIDatatype_Type.tp_print = 0;\n     3710           |                     ^\n  >> 3711    src/mpi4py.MPI.c:160866:20: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3712    160866 |   PyMPIRequest_Type.tp_print = 0;\n     3713           |                    ^\n>> 3714    src/mpi4py.MPI.c:160874:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3715    160874 |   PyMPIPrequest_Type.tp_print = 0;\n     3716           |                     ^\n  >> 3717    src/mpi4py.MPI.c:160882:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3718    160882 |   PyMPIGrequest_Type.tp_print = 0;",
    "3712    160866 |   PyMPIRequest_Type.tp_print = 0;\n     3713           |                    ^\n  >> 3714    src/mpi4py.MPI.c:160874:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3715    160874 |   PyMPIPrequest_Type.tp_print = 0;\n     3716           |                     ^\n>> 3717    src/mpi4py.MPI.c:160882:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3718    160882 |   PyMPIGrequest_Type.tp_print = 0;\n     3719           |                     ^\n  >> 3720    src/mpi4py.MPI.c:160889:20: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3721    160889 |   PyMPIMessage_Type.tp_print = 0;",
    "3715    160874 |   PyMPIPrequest_Type.tp_print = 0;\n     3716           |                     ^\n  >> 3717    src/mpi4py.MPI.c:160882:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3718    160882 |   PyMPIGrequest_Type.tp_print = 0;\n     3719           |                     ^\n>> 3720    src/mpi4py.MPI.c:160889:20: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3721    160889 |   PyMPIMessage_Type.tp_print = 0;\n     3722           |                    ^\n  >> 3723    src/mpi4py.MPI.c:160896:15: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3724    160896 |   PyMPIOp_Type.tp_print = 0;",
    "3718    160882 |   PyMPIGrequest_Type.tp_print = 0;\n     3719           |                     ^\n  >> 3720    src/mpi4py.MPI.c:160889:20: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3721    160889 |   PyMPIMessage_Type.tp_print = 0;\n     3722           |                    ^\n>> 3723    src/mpi4py.MPI.c:160896:15: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3724    160896 |   PyMPIOp_Type.tp_print = 0;\n     3725           |               ^\n  >> 3726    src/mpi4py.MPI.c:160903:18: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3727    160903 |   PyMPIGroup_Type.tp_print = 0;",
    "3721    160889 |   PyMPIMessage_Type.tp_print = 0;\n     3722           |                    ^\n  >> 3723    src/mpi4py.MPI.c:160896:15: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3724    160896 |   PyMPIOp_Type.tp_print = 0;\n     3725           |               ^\n>> 3726    src/mpi4py.MPI.c:160903:18: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3727    160903 |   PyMPIGroup_Type.tp_print = 0;\n     3728           |                  ^\n  >> 3729    src/mpi4py.MPI.c:160910:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3730    160910 |   PyMPIInfo_Type.tp_print = 0;",
    "3724    160896 |   PyMPIOp_Type.tp_print = 0;\n     3725           |               ^\n  >> 3726    src/mpi4py.MPI.c:160903:18: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3727    160903 |   PyMPIGroup_Type.tp_print = 0;\n     3728           |                  ^\n>> 3729    src/mpi4py.MPI.c:160910:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3730    160910 |   PyMPIInfo_Type.tp_print = 0;\n     3731           |                 ^\n  >> 3732    src/mpi4py.MPI.c:160917:23: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3733    160917 |   PyMPIErrhandler_Type.tp_print = 0;",
    "3727    160903 |   PyMPIGroup_Type.tp_print = 0;\n     3728           |                  ^\n  >> 3729    src/mpi4py.MPI.c:160910:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3730    160910 |   PyMPIInfo_Type.tp_print = 0;\n     3731           |                 ^\n>> 3732    src/mpi4py.MPI.c:160917:23: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3733    160917 |   PyMPIErrhandler_Type.tp_print = 0;\n     3734           |                       ^\n  >> 3735    src/mpi4py.MPI.c:160924:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3736    160924 |   PyMPIComm_Type.tp_print = 0;",
    "3730    160910 |   PyMPIInfo_Type.tp_print = 0;\n     3731           |                 ^\n  >> 3732    src/mpi4py.MPI.c:160917:23: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3733    160917 |   PyMPIErrhandler_Type.tp_print = 0;\n     3734           |                       ^\n>> 3735    src/mpi4py.MPI.c:160924:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3736    160924 |   PyMPIComm_Type.tp_print = 0;\n     3737           |                 ^\n  >> 3738    src/mpi4py.MPI.c:160932:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3739    160932 |   PyMPIIntracomm_Type.tp_print = 0;",
    "3733    160917 |   PyMPIErrhandler_Type.tp_print = 0;\n     3734           |                       ^\n  >> 3735    src/mpi4py.MPI.c:160924:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3736    160924 |   PyMPIComm_Type.tp_print = 0;\n     3737           |                 ^\n>> 3738    src/mpi4py.MPI.c:160932:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3739    160932 |   PyMPIIntracomm_Type.tp_print = 0;\n     3740           |                      ^\n  >> 3741    src/mpi4py.MPI.c:160940:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3742    160940 |   PyMPITopocomm_Type.tp_print = 0;",
    "3736    160924 |   PyMPIComm_Type.tp_print = 0;\n     3737           |                 ^\n  >> 3738    src/mpi4py.MPI.c:160932:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3739    160932 |   PyMPIIntracomm_Type.tp_print = 0;\n     3740           |                      ^\n>> 3741    src/mpi4py.MPI.c:160940:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3742    160940 |   PyMPITopocomm_Type.tp_print = 0;\n     3743           |                     ^\n  >> 3744    src/mpi4py.MPI.c:160948:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3745    160948 |   PyMPICartcomm_Type.tp_print = 0;",
    "3739    160932 |   PyMPIIntracomm_Type.tp_print = 0;\n     3740           |                      ^\n  >> 3741    src/mpi4py.MPI.c:160940:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3742    160940 |   PyMPITopocomm_Type.tp_print = 0;\n     3743           |                     ^\n>> 3744    src/mpi4py.MPI.c:160948:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3745    160948 |   PyMPICartcomm_Type.tp_print = 0;\n     3746           |                     ^\n  >> 3747    src/mpi4py.MPI.c:160956:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3748    160956 |   PyMPIGraphcomm_Type.tp_print = 0;",
    "3742    160940 |   PyMPITopocomm_Type.tp_print = 0;\n     3743           |                     ^\n  >> 3744    src/mpi4py.MPI.c:160948:21: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3745    160948 |   PyMPICartcomm_Type.tp_print = 0;\n     3746           |                     ^\n>> 3747    src/mpi4py.MPI.c:160956:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3748    160956 |   PyMPIGraphcomm_Type.tp_print = 0;\n     3749           |                      ^\n  >> 3750    src/mpi4py.MPI.c:160964:26: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3751    160964 |   PyMPIDistgraphcomm_Type.tp_print = 0;",
    "3745    160948 |   PyMPICartcomm_Type.tp_print = 0;\n     3746           |                     ^\n  >> 3747    src/mpi4py.MPI.c:160956:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3748    160956 |   PyMPIGraphcomm_Type.tp_print = 0;\n     3749           |                      ^\n>> 3750    src/mpi4py.MPI.c:160964:26: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3751    160964 |   PyMPIDistgraphcomm_Type.tp_print = 0;\n     3752           |                          ^\n  >> 3753    src/mpi4py.MPI.c:160972:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3754    160972 |   PyMPIIntercomm_Type.tp_print = 0;",
    "3748    160956 |   PyMPIGraphcomm_Type.tp_print = 0;\n     3749           |                      ^\n  >> 3750    src/mpi4py.MPI.c:160964:26: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3751    160964 |   PyMPIDistgraphcomm_Type.tp_print = 0;\n     3752           |                          ^\n>> 3753    src/mpi4py.MPI.c:160972:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3754    160972 |   PyMPIIntercomm_Type.tp_print = 0;\n     3755           |                      ^\n  >> 3756    src/mpi4py.MPI.c:160979:16: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3757    160979 |   PyMPIWin_Type.tp_print = 0;",
    "3751    160964 |   PyMPIDistgraphcomm_Type.tp_print = 0;\n     3752           |                          ^\n  >> 3753    src/mpi4py.MPI.c:160972:22: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3754    160972 |   PyMPIIntercomm_Type.tp_print = 0;\n     3755           |                      ^\n>> 3756    src/mpi4py.MPI.c:160979:16: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3757    160979 |   PyMPIWin_Type.tp_print = 0;\n     3758           |                ^\n  >> 3759    src/mpi4py.MPI.c:160986:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3760    160986 |   PyMPIFile_Type.tp_print = 0;",
    "3754    160972 |   PyMPIIntercomm_Type.tp_print = 0;\n     3755           |                      ^\n  >> 3756    src/mpi4py.MPI.c:160979:16: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3757    160979 |   PyMPIWin_Type.tp_print = 0;\n     3758           |                ^\n>> 3759    src/mpi4py.MPI.c:160986:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3760    160986 |   PyMPIFile_Type.tp_print = 0;\n     3761           |                 ^\n  >> 3762    src/mpi4py.MPI.c:160993:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3763    160993 |   __pyx_type_6mpi4py_3MPI_memory.tp_print = 0;",
    "3757    160979 |   PyMPIWin_Type.tp_print = 0;\n     3758           |                ^\n  >> 3759    src/mpi4py.MPI.c:160986:17: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3760    160986 |   PyMPIFile_Type.tp_print = 0;\n     3761           |                 ^\n>> 3762    src/mpi4py.MPI.c:160993:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3763    160993 |   __pyx_type_6mpi4py_3MPI_memory.tp_print = 0;\n     3764           |                                 ^\n  >> 3765    src/mpi4py.MPI.c:161000:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3766    161000 |   __pyx_type_6mpi4py_3MPI__p_mem.tp_print = 0;",
    "3760    160986 |   PyMPIFile_Type.tp_print = 0;\n     3761           |                 ^\n  >> 3762    src/mpi4py.MPI.c:160993:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3763    160993 |   __pyx_type_6mpi4py_3MPI_memory.tp_print = 0;\n     3764           |                                 ^\n>> 3765    src/mpi4py.MPI.c:161000:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3766    161000 |   __pyx_type_6mpi4py_3MPI__p_mem.tp_print = 0;\n     3767           |                                 ^\n  >> 3768    src/mpi4py.MPI.c:161010:34: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3769    161010 |   __pyx_type_6mpi4py_3MPI__p_greq.tp_print = 0;",
    "3763    160993 |   __pyx_type_6mpi4py_3MPI_memory.tp_print = 0;\n     3764           |                                 ^\n  >> 3765    src/mpi4py.MPI.c:161000:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3766    161000 |   __pyx_type_6mpi4py_3MPI__p_mem.tp_print = 0;\n     3767           |                                 ^\n>> 3768    src/mpi4py.MPI.c:161010:34: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3769    161010 |   __pyx_type_6mpi4py_3MPI__p_greq.tp_print = 0;\n     3770           |                                  ^\n  >> 3771    src/mpi4py.MPI.c:161021:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3772    161021 |   __pyx_type_6mpi4py_3MPI__p_datarep.tp_print = 0;",
    "3766    161000 |   __pyx_type_6mpi4py_3MPI__p_mem.tp_print = 0;\n     3767           |                                 ^\n  >> 3768    src/mpi4py.MPI.c:161010:34: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3769    161010 |   __pyx_type_6mpi4py_3MPI__p_greq.tp_print = 0;\n     3770           |                                  ^\n>> 3771    src/mpi4py.MPI.c:161021:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3772    161021 |   __pyx_type_6mpi4py_3MPI__p_datarep.tp_print = 0;\n     3773           |                                     ^\n  >> 3774    src/mpi4py.MPI.c:161028:36: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3775    161028 |   __pyx_type_6mpi4py_3MPI__p_keyval.tp_print = 0;",
    "3769    161010 |   __pyx_type_6mpi4py_3MPI__p_greq.tp_print = 0;\n     3770           |                                  ^\n  >> 3771    src/mpi4py.MPI.c:161021:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3772    161021 |   __pyx_type_6mpi4py_3MPI__p_datarep.tp_print = 0;\n     3773           |                                     ^\n>> 3774    src/mpi4py.MPI.c:161028:36: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3775    161028 |   __pyx_type_6mpi4py_3MPI__p_keyval.tp_print = 0;\n     3776           |                                    ^\n  >> 3777    src/mpi4py.MPI.c:161034:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3778    161034 |   __pyx_type_6mpi4py_3MPI__p_message.tp_print = 0;",
    "3772    161021 |   __pyx_type_6mpi4py_3MPI__p_datarep.tp_print = 0;\n     3773           |                                     ^\n  >> 3774    src/mpi4py.MPI.c:161028:36: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3775    161028 |   __pyx_type_6mpi4py_3MPI__p_keyval.tp_print = 0;\n     3776           |                                    ^\n>> 3777    src/mpi4py.MPI.c:161034:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3778    161034 |   __pyx_type_6mpi4py_3MPI__p_message.tp_print = 0;\n     3779           |                                     ^\n  >> 3780    src/mpi4py.MPI.c:161043:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3781    161043 |   __pyx_type_6mpi4py_3MPI__p_msg_p2p.tp_print = 0;",
    "3775    161028 |   __pyx_type_6mpi4py_3MPI__p_keyval.tp_print = 0;\n     3776           |                                    ^\n  >> 3777    src/mpi4py.MPI.c:161034:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3778    161034 |   __pyx_type_6mpi4py_3MPI__p_message.tp_print = 0;\n     3779           |                                     ^\n>> 3780    src/mpi4py.MPI.c:161043:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3781    161043 |   __pyx_type_6mpi4py_3MPI__p_msg_p2p.tp_print = 0;\n     3782           |                                     ^\n  >> 3783    src/mpi4py.MPI.c:161068:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3784    161068 |   __pyx_type_6mpi4py_3MPI__p_msg_cco.tp_print = 0;",
    "3778    161034 |   __pyx_type_6mpi4py_3MPI__p_message.tp_print = 0;\n     3779           |                                     ^\n  >> 3780    src/mpi4py.MPI.c:161043:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3781    161043 |   __pyx_type_6mpi4py_3MPI__p_msg_p2p.tp_print = 0;\n     3782           |                                     ^\n>> 3783    src/mpi4py.MPI.c:161068:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3784    161068 |   __pyx_type_6mpi4py_3MPI__p_msg_cco.tp_print = 0;\n     3785           |                                     ^\n  >> 3786    src/mpi4py.MPI.c:161078:38: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3787    161078 |   __pyx_type_6mpi4py_3MPI__p_msg_ccow.tp_print = 0;",
    "3781    161043 |   __pyx_type_6mpi4py_3MPI__p_msg_p2p.tp_print = 0;\n     3782           |                                     ^\n  >> 3783    src/mpi4py.MPI.c:161068:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3784    161068 |   __pyx_type_6mpi4py_3MPI__p_msg_cco.tp_print = 0;\n     3785           |                                     ^\n>> 3786    src/mpi4py.MPI.c:161078:38: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3787    161078 |   __pyx_type_6mpi4py_3MPI__p_msg_ccow.tp_print = 0;\n     3788           |                                      ^\n  >> 3789    src/mpi4py.MPI.c:161096:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3790    161096 |   __pyx_type_6mpi4py_3MPI__p_msg_rma.tp_print = 0;",
    "3784    161068 |   __pyx_type_6mpi4py_3MPI__p_msg_cco.tp_print = 0;\n     3785           |                                     ^\n  >> 3786    src/mpi4py.MPI.c:161078:38: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3787    161078 |   __pyx_type_6mpi4py_3MPI__p_msg_ccow.tp_print = 0;\n     3788           |                                      ^\n>> 3789    src/mpi4py.MPI.c:161096:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3790    161096 |   __pyx_type_6mpi4py_3MPI__p_msg_rma.tp_print = 0;\n     3791           |                                     ^\n  >> 3792    src/mpi4py.MPI.c:161106:36: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3793    161106 |   __pyx_type_6mpi4py_3MPI__p_msg_io.tp_print = 0;",
    "3787    161078 |   __pyx_type_6mpi4py_3MPI__p_msg_ccow.tp_print = 0;\n     3788           |                                      ^\n  >> 3789    src/mpi4py.MPI.c:161096:37: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3790    161096 |   __pyx_type_6mpi4py_3MPI__p_msg_rma.tp_print = 0;\n     3791           |                                     ^\n>> 3792    src/mpi4py.MPI.c:161106:36: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3793    161106 |   __pyx_type_6mpi4py_3MPI__p_msg_io.tp_print = 0;\n     3794           |                                    ^\n  >> 3795    src/mpi4py.MPI.c:161122:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3796    161122 |   __pyx_type_6mpi4py_3MPI_Pickle.tp_print = 0;",
    "3790    161096 |   __pyx_type_6mpi4py_3MPI__p_msg_rma.tp_print = 0;\n     3791           |                                     ^\n  >> 3792    src/mpi4py.MPI.c:161106:36: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3793    161106 |   __pyx_type_6mpi4py_3MPI__p_msg_io.tp_print = 0;\n     3794           |                                    ^\n>> 3795    src/mpi4py.MPI.c:161122:33: error: 'PyTypeObject' {aka 'struct _ty\n             peobject'} has no member named 'tp_print'\n     3796    161122 |   __pyx_type_6mpi4py_3MPI_Pickle.tp_print = 0;\n     3797           |                                 ^\n     3798    src/mpi4py.MPI.c: In function '__Pyx_ParseOptionalKeywords':\n     3799    src/mpi4py.MPI.c:174013:21: warning: '_PyUnicode_get_wstr_length'\n             is deprecated [-Wdeprecated-declarations]"
]