[
    "51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign\n            -compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-mpe.c -o build/t\n            emp.linux-x86_64-3.9/src/pmpi-mpe.o\n53     src/pmpi-mpe.c:3:19: warning: 'name' defined but not used [-Wunused\n            -const-variable=]\n     54         3 | static const char name[] = \"mpe\";\n     55           |                   ^~~~\n     56     creating build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi\n     57     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu",
    "94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign\n            -compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-mpi.c -o buil\n            d/temp.linux-x86_64-3.9/src/pmpi-vt-mpi.o\n96     src/pmpi-vt-mpi.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     97         3 | static const char name[] = \"vt-mpi\";\n     98           |                   ^~~~\n     99     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc /p/vast1/koparasy/BUILD/head/sp",
    "113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign\n            -compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-hyb.c -o buil\n            d/temp.linux-x86_64-3.9/src/pmpi-vt-hyb.o\n115    src/pmpi-vt-hyb.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     116        3 | static const char name[] = \"vt-hyb\";\n     117          |                   ^~~~\n     118    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc /p/vast1/koparasy/BUILD/head/sp",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':\n235    src/mpi4py.MPI.c:113239:9: warning: 'PyEval_CallObjectWithKeywords'\n             is deprecated [-Wdeprecated-declarations]\n     236    113239 |         owned_instance = PyEval_CallObject(type, args);\n\n     ...\n\n     395                     from src/MPI.c:3:",
    "51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws\n            ign-compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-mpe.c -o buil\n            d/temp.linux-x86_64-3.9/src/pmpi-mpe.o\n53     src/pmpi-mpe.c:3:19: warning: 'name' defined but not used [-Wunused\n            -const-variable=]\n     54         3 | static const char name[] = \"mpe\";\n     55           |                   ^~~~\n     56     creating build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi\n     57     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4",
    "94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws\n            ign-compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-mpi.c -o b\n            uild/temp.linux-x86_64-3.9/src/pmpi-vt-mpi.o\n96     src/pmpi-vt-mpi.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     97         3 | static const char name[] = \"vt-mpi\";\n     98           |                   ^~~~\n     99     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc /p/vast1/koparasy/BUILD/head",
    "113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws\n            ign-compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-hyb.c -o b\n            uild/temp.linux-x86_64-3.9/src/pmpi-vt-hyb.o\n115    src/pmpi-vt-hyb.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     116        3 | static const char name[] = \"vt-hyb\";\n     117          |                   ^~~~\n     118    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc /p/vast1/koparasy/BUILD/head",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':\n235    src/mpi4py.MPI.c:113239:9: warning: 'PyEval_CallObjectWithKeywords'\n             is deprecated [-Wdeprecated-declarations]\n     236    113239 |         owned_instance = PyEval_CallObject(type, args);\n\n     ...\n\n     395                     from src/MPI.c:3:",
    "igtest.o\n     37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lmpe -lpthrea\n            d -o _configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lmpe\n  >> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4",
    "37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lmpe -lpthrea\n            d -o _configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lmpe\n>> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws",
    "igtest.o\n     44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -llmpe -lpthre\n            ad -o _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -llmpe\n  >> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src",
    "44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -llmpe -lpthre\n            ad -o _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -llmpe\n>> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb",
    "z/py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib\n            -1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_6\n            4-3.9/src/pmpi-mpe.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/\n            libmpe.so\n     58     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 59     collect2: error: ld returned 1 exit status\n     60     warning: build_clib: building library \"mpe\" failed\n     61\n     62     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpic\n            c' failed with exit code 1",
    "igtest.o\n     66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _c\n            onfigtest\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4",
    "66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _c\n            onfigtest\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws",
    "igtest.o\n     73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt.mpi -o _c\n            onfigtest\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt.mpi\n  >> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4",
    "73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt.mpi -o _c\n            onfigtest\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt.mpi\n>> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws",
    "z/py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib\n            -1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_6\n            4-3.9/src/pmpi-vt.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/l\n            ibvt.so\n     81     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 82     collect2: error: ld returned 1 exit status\n     83     warning: build_clib: building library \"vt\" failed\n     84\n     85     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpic\n            c' failed with exit code 1",
    "igtest.o\n     89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _c\n            onfigtest\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4",
    "89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _c\n            onfigtest\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws",
    "z/py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib\n            -1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_6\n            4-3.9/src/pmpi-vt-mpi.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pm\n            pi/libvt-mpi.so\n     100    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 101    collect2: error: ld returned 1 exit status\n     102    warning: build_clib: building library \"vt-mpi\" failed\n     103\n     104    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpic\n            c' failed with exit code 1",
    "igtest.o\n     108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-hyb -o _c\n            onfigtest\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-hyb\n  >> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4",
    "108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-hyb -o _c\n            onfigtest\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-hyb\n>> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4\n            wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Ws",
    "z/py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib\n            -1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_6\n            4-3.9/src/pmpi-vt-hyb.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pm\n            pi/libvt-hyb.so\n     119    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 120    collect2: error: ld returned 1 exit status\n     121    warning: build_clib: building library \"vt-hyb\" failed\n     122\n     123    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpic\n            c' failed with exit code 1",
    "te: declared here\n     206      334 | Py_DEPRECATED(3.0) PyAPI_FUNC(int) PyObject_CheckReadBuffer\n            (PyObject *obj);\n     207          |                                    ^~~~~~~~~~~~~~~~~~~~~~~~\n     208    In file included from src/MPI.c:3:\n     209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n>> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n  >> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n>> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n  >> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n>> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n>> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n>> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n  >> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n>> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':",
    "note: declared here\n     397       33 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyCFunction_Call(\n            PyObject *, PyObject *, PyObject *);\n     398          |                                           ^~~~~~~~~~~~~~~~\n     399    In file included from src/MPI.c:3:\n     400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n>> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n  >> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n>> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n  >> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n>> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n>> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n  >> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n>> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n  >> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n>> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n>> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n>> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n  >> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n>> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     435    114588 |     tstate->exc_traceback = tb;\n     436           |             ^~~~~~~~~~~~~\n     437           |             curexc_traceback\n  >> 438    error: command '/p/vast1/koparasy/BUILD/spack_cluster_installer/qua",
    "51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co\n            mpare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-mpe.c -o build/temp\n            .linux-x86_64-3.9/src/pmpi-mpe.o\n53     src/pmpi-mpe.c:3:19: warning: 'name' defined but not used [-Wunused\n            -const-variable=]\n     54         3 | static const char name[] = \"mpe\";\n     55           |                   ^~~~\n     56     creating build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi\n     57     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc",
    "94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co\n            mpare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-mpi.c -o build/t\n            emp.linux-x86_64-3.9/src/pmpi-vt-mpi.o\n96     src/pmpi-vt-mpi.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     97         3 | static const char name[] = \"vt-mpi\";\n     98           |                   ^~~~\n     99     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc /p/vast1/koparasy/BUILD/head/spack",
    "113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co\n            mpare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-hyb.c -o build/t\n            emp.linux-x86_64-3.9/src/pmpi-vt-hyb.o\n115    src/pmpi-vt-hyb.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     116        3 | static const char name[] = \"vt-hyb\";\n     117          |                   ^~~~\n     118    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc /p/vast1/koparasy/BUILD/head/spack",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':\n235    src/mpi4py.MPI.c:113239:9: warning: 'PyEval_CallObjectWithKeywords'\n             is deprecated [-Wdeprecated-declarations]\n     236    113239 |         owned_instance = PyEval_CallObject(type, args);\n\n     ...\n\n     395                     from src/MPI.c:3:",
    "est.o\n     37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lmpe -lpthread -\n            o _configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lmpe\n  >> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu",
    "37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lmpe -lpthread -\n            o _configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lmpe\n>> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign",
    "est.o\n     44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -llmpe -lpthread\n            -o _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -llmpe\n  >> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src",
    "44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -llmpe -lpthread\n            -o _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -llmpe\n>> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/",
    "D/spack_cluster_installer/quartz/py-petsc4py/spack_env_dir/linux-rh\n            el7-broadwell/gcc-9.3.1/zlib-1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizz\n            u/lib build/temp.linux-x86_64-3.9/src/pmpi-mpe.o -o build/lib.linux\n            -x86_64-3.9/mpi4py/lib-pmpi/libmpe.so\n     58     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 59     collect2: error: ld returned 1 exit status\n     60     warning: build_clib: building library \"mpe\" failed\n     61\n     62     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-petsc4py/spack_env_dir/linux-rhel7-broadwell/g\n            cc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc'\n            failed with exit code 1",
    "est.o\n     66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _conf\n            igtest\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu",
    "66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _conf\n            igtest\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign",
    "est.o\n     73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt.mpi -o _conf\n            igtest\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt.mpi\n  >> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu",
    "73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt.mpi -o _conf\n            igtest\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt.mpi\n>> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign",
    "D/spack_cluster_installer/quartz/py-petsc4py/spack_env_dir/linux-rh\n            el7-broadwell/gcc-9.3.1/zlib-1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizz\n            u/lib build/temp.linux-x86_64-3.9/src/pmpi-vt.o -o build/lib.linux-\n            x86_64-3.9/mpi4py/lib-pmpi/libvt.so\n     81     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 82     collect2: error: ld returned 1 exit status\n     83     warning: build_clib: building library \"vt\" failed\n     84\n     85     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-petsc4py/spack_env_dir/linux-rhel7-broadwell/g\n            cc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc'\n            failed with exit code 1",
    "est.o\n     89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _conf\n            igtest\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu",
    "89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _conf\n            igtest\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign",
    "D/spack_cluster_installer/quartz/py-petsc4py/spack_env_dir/linux-rh\n            el7-broadwell/gcc-9.3.1/zlib-1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizz\n            u/lib build/temp.linux-x86_64-3.9/src/pmpi-vt-mpi.o -o build/lib.li\n            nux-x86_64-3.9/mpi4py/lib-pmpi/libvt-mpi.so\n     100    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 101    collect2: error: ld returned 1 exit status\n     102    warning: build_clib: building library \"vt-mpi\" failed\n     103\n     104    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-petsc4py/spack_env_dir/linux-rhel7-broadwell/g\n            cc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc'\n            failed with exit code 1",
    "est.o\n     108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-hyb -o _conf\n            igtest\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-hyb\n  >> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu",
    "108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-hyb -o _conf\n            igtest\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-hyb\n>> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-petsc4py/\n            spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqu\n            djcg7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign",
    "D/spack_cluster_installer/quartz/py-petsc4py/spack_env_dir/linux-rh\n            el7-broadwell/gcc-9.3.1/zlib-1.2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizz\n            u/lib build/temp.linux-x86_64-3.9/src/pmpi-vt-hyb.o -o build/lib.li\n            nux-x86_64-3.9/mpi4py/lib-pmpi/libvt-hyb.so\n     119    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 120    collect2: error: ld returned 1 exit status\n     121    warning: build_clib: building library \"vt-hyb\" failed\n     122\n     123    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-petsc4py/spack_env_dir/linux-rhel7-broadwell/g\n            cc-9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc'\n            failed with exit code 1",
    "declared here\n     206      334 | Py_DEPRECATED(3.0) PyAPI_FUNC(int) PyObject_CheckReadBuffer\n            (PyObject *obj);\n     207          |                                    ^~~~~~~~~~~~~~~~~~~~~~~~\n     208    In file included from src/MPI.c:3:\n     209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n>> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n  >> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n>> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n  >> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n>> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n>> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n>> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n  >> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n>> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':",
    "te: declared here\n     397       33 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyCFunction_Call(\n            PyObject *, PyObject *, PyObject *);\n     398          |                                           ^~~~~~~~~~~~~~~~\n     399    In file included from src/MPI.c:3:\n     400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n>> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n  >> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n>> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n  >> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n>> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n>> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n  >> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n>> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n  >> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n>> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n>> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n>> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n  >> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n>> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     435    114588 |     tstate->exc_traceback = tb;\n     436           |             ^~~~~~~~~~~~~\n     437           |             curexc_traceback\n  >> 438    error: command '/p/vast1/koparasy/BUILD/spack_cluster_installer/qua",
    ".o\n     37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lmpe -lpthread -o _\n            configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lmpe\n  >> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc",
    "37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lmpe -lpthread -o _\n            configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lmpe\n>> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co",
    ".o\n     44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -llmpe -lpthread -o\n            _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -llmpe\n  >> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src",
    "44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -llmpe -lpthread -o\n            _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -llmpe\n>> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa",
    "a5/lib -L/p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-\n            warpx/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1.2.11-dtz\n            zlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-3.9/src/p\n            mpi-mpe.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/libmpe.so\n     58     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 59     collect2: error: ld returned 1 exit status\n     60     warning: build_clib: building library \"mpe\" failed\n     61\n     62     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-warpx/spack_env_dir/linux-rhel7-broadwell/gcc-\n            9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc' fai\n            led with exit code 1",
    ".o\n     66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _configt\n            est\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc",
    "66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _configt\n            est\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co",
    ".o\n     73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt.mpi -o _configt\n            est\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt.mpi\n  >> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc",
    "73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt.mpi -o _configt\n            est\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt.mpi\n>> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co",
    "a5/lib -L/p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-\n            warpx/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1.2.11-dtz\n            zlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-3.9/src/p\n            mpi-vt.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/libvt.so\n     81     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 82     collect2: error: ld returned 1 exit status\n     83     warning: build_clib: building library \"vt\" failed\n     84\n     85     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-warpx/spack_env_dir/linux-rhel7-broadwell/gcc-\n            9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc' fai\n            led with exit code 1",
    ".o\n     89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _configt\n            est\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc",
    "89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-mpi -o _configt\n            est\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co",
    "warpx/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1.2.11-dtz\n            zlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-3.9/src/p\n            mpi-vt-mpi.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/libvt-mp\n            i.so\n     100    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 101    collect2: error: ld returned 1 exit status\n     102    warning: build_clib: building library \"vt-mpi\" failed\n     103\n     104    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-warpx/spack_env_dir/linux-rhel7-broadwell/gcc-\n            9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc' fai\n            led with exit code 1",
    ".o\n     108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-hyb -o _configt\n            est\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-hyb\n  >> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc",
    "108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc _configtest.o -lvt-hyb -o _configt\n            est\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-hyb\n>> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-warpx/spa\n            ck_env_dir/linux-rhel7-broadwell/gcc-9.3.1/openmpi-4.1.2-jav4wqudjc\n            g7dsjv2bfmiftfzddznkg3/bin/mpicc -fPIC -Wno-unused-result -Wsign-co",
    "warpx/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1.2.11-dtz\n            zlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-3.9/src/p\n            mpi-vt-hyb.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/libvt-hy\n            b.so\n     119    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 120    collect2: error: ld returned 1 exit status\n     121    warning: build_clib: building library \"vt-hyb\" failed\n     122\n     123    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-warpx/spack_env_dir/linux-rhel7-broadwell/gcc-\n            9.3.1/openmpi-4.1.2-jav4wqudjcg7dsjv2bfmiftfzddznkg3/bin/mpicc' fai\n            led with exit code 1",
    "clared here\n     206      334 | Py_DEPRECATED(3.0) PyAPI_FUNC(int) PyObject_CheckReadBuffer\n            (PyObject *obj);\n     207          |                                    ^~~~~~~~~~~~~~~~~~~~~~~~\n     208    In file included from src/MPI.c:3:\n     209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n>> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n  >> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n>> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n  >> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n>> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n>> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n>> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n  >> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n>> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':",
    "declared here\n     397       33 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyCFunction_Call(\n            PyObject *, PyObject *, PyObject *);\n     398          |                                           ^~~~~~~~~~~~~~~~\n     399    In file included from src/MPI.c:3:\n     400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n>> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n  >> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n>> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n  >> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n>> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n>> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n  >> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n>> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n  >> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n>> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n>> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n>> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n  >> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n>> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     435    114588 |     tstate->exc_traceback = tb;\n     436           |             ^~~~~~~~~~~~~\n     437           |             curexc_traceback\n  >> 438    error: command '/p/vast1/koparasy/BUILD/spack_cluster_installer/qua"
]